- hosts: localhost
  become: true
  vars_files:
    - ./vars/main.yaml
  tasks:
#  - name: install bind
#    package:
#      name: bind
#      state: latest
  
  - name: Copy Named.conf
    template:
      src: named.conf.j2
      dest: /etc/named.conf 
      force: yes
      group: named
      mode: 0640
  
  - name: Copy zone files
    template:
      src: example.com.zone.j2
      dest: /var/named/example.com.zone
      force: yes

  - name: Start and enable dns service
    service:
      name: named
      state: started
      enabled: yes
  
  - debug: var=groups
  - debug: var=hostvars
  - debug: 
      var: item
    loop: "{{ groups.all }}"

  - name: Insert host A records
    lineinfile:
      path: /var/named/example.com.zone
      state: present
      regexp: EOF
      line: "{{ item }} IN  A {{ hostvars[item]['ansible_host'] }}"
    loop: "{{ groups.all }}"
    notify: restart dns

  handlers:
  - name: restart dns
    service:
      name: named
      state: restarted
      enabled: yes

